name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.GH_PAGES}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa

      - name: Git config
        run: |
          git config --global user.email "auto-user@auto-github-deploy.com"
          git config --global user.name "auto-user"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- -r git@github.com:jesusbm90/auto-github-deploy.git
